#!/bin/sh

PREREQ=""

prereqs()
{
	echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
	prereqs
	exit 0
	;;
esac

# blacklist vga16fb when vga= or video= given
for x in $(cat /proc/cmdline); do
        case ${x} in
	vga=*|video=*)
		echo "blacklist vga16fb" >> /etc/modprobe.d/initramfs.conf
		;;
	esac
done

#
# Prevent dwc3 (Synopsys DesignWare Core SuperSpeed USB 3.0 driver) module from
# taking MN-Core device(s)
#
# Added by PFN Chip team <chip-team@preferred.jp> - 2019/06/19
echo "blacklist dwc3" >> /etc/modprobe.d/initramfs.conf
echo "blacklist dwc3_pci" >> /etc/modprobe.d/initramfs.conf

# sanity check
[ -z "${blacklist}" ] && exit 0

# write blacklist to modprobe.d
IFS=','
for b in ${blacklist}; do
	echo "blacklist $b" >> /etc/modprobe.d/initramfs.conf
done
